import path from "node:path";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

const db = (p: string) => path.resolve(__dirname, `packages/database/src/${p}`);
const shared = (p: string) => path.resolve(__dirname, `packages/shared/src/${p}`);
const ui = (p: string) => path.resolve(__dirname, `packages/ui/src/${p}`);
const adminApp = (p: string) => path.resolve(__dirname, `apps/admin/${p}`);
const mainApp = (p: string) => path.resolve(__dirname, `apps/main/${p}`);
// Canonical paths for packages that exist in multiple symlinked locations (pnpm workspaces)
// This ensures vi.mock() intercepts imports regardless of which symlink path resolves them.
const supabaseSsr = path.resolve(__dirname, "packages/database/node_modules/@supabase/ssr");
const nextHeaders = path.resolve(__dirname, "packages/database/node_modules/next/headers");

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "node",
    environmentMatchGlobs: [["tests/components/**", "jsdom"]],
    globals: true,
    include: [
      "tests/unit/**/*.{test,spec}.{ts,tsx}",
      "tests/integration/**/*.{test,spec}.{ts,tsx}",
      "tests/security/**/*.{test,spec}.{ts,tsx}",
      "tests/components/**/*.{test,spec}.{ts,tsx}",
    ],
    setupFiles: ["./tests/setup.ts", "./tests/unit/setup.ts"],
    alias: {
      "@supabase/ssr": supabaseSsr,
      "next/headers": nextHeaders,
      // Admin-side helpers import the canonical workspace package path
      // (@workspace/database/lib/idempotency). Alias it so vi.mock() can
      // intercept tests that exercise those helpers.
      "@workspace/database/lib/idempotency": db("lib/idempotency"),
      "@workspace/shared/constants": shared("constants"),
      "@workspace/shared/http-status": shared("http-status"),
      "@workspace/shared/pagination": shared("pagination"),
      "@workspace/shared/api-endpoints": shared("api-endpoints"),
      "@workspace/shared/analytics": shared("analytics"),
      "@workspace/shared/api-client": shared("api-client"),
      "@workspace/shared/utils": shared("utils"),
      "@workspace/shared/schemas": shared("schemas"),
      "@workspace/shared/routes": shared("routes"),
      "@workspace/shared": shared("index"),
      "@/db/db.server": db("db"),
      "@/db": db(""),
      "@/lib/security.server": db("lib/security"),
      "@/lib/auth.server": db("lib/auth"),
      "@/lib/db-locking": db("lib/db-locking"),
      "@/lib/supabase/admin": db("lib/supabase/admin"),
      "@/lib/supabase/server": db("lib/supabase/server"),
      "@/lib/supabase/client": db("lib/supabase/client"),
      "@/lib/supabase": db("lib/supabase"),
      "@/utils/supabase/server": db("lib/supabase/server"),
      "@/utils/supabase/client": db("lib/supabase/client"),
      "@/utils/supabase/admin": db("lib/supabase/admin"),
      "@/lib/http-status": shared("http-status"),
      "@/lib/pagination": shared("pagination"),
      "@/lib/api-endpoints": shared("api-endpoints"),
      "@/lib/api-client": shared("api-client"),
      "@/lib/utils": shared("utils"),
      "@/lib/schemas": shared("schemas"),
      "@/lib/api-auth": adminApp("lib/api-auth"),
      "@/lib/date-range": adminApp("lib/date-range"),
      "@/lib/idempotency": adminApp("lib/idempotency"),
      "@/lib": shared(""),
      "@/services/admin.client": adminApp("services/admin.client"),
      "@/services/chat.client": mainApp("services/chat.client"),
      "@/services/banner.server": db("services/banner.server"),
      "@/services/categoryCard.server": db("services/categoryCard.server"),
      "@/services": db("services"),
      "@/components/admin": adminApp("components/admin"),
      "@/components/store": mainApp("components/store"),
      "@/components/account": mainApp("components/account"),
      "@/components/products": mainApp("components/products"),
      "@/components/sections": mainApp("components/sections"),
      "@/components/layout": mainApp("components/layout"),
      "@/components/ui": ui("components"),
      "@/components/image-uploader": adminApp("components/image-uploader"),
      "@/components": mainApp("components"),
      "@/hooks/useMobile": ui("hooks/use-mobile"),
      "@/hooks": mainApp("hooks"),
      "@/types/admin": db("types/admin"),
      "@/types/api": db("types/api"),
      "@/types/database": db("types/database"),
      "@/types/order": db("types/order"),
      "@/types": shared("types"),
      "@/agent": mainApp("agent"),
      "@/app/api/admin": adminApp("app/api/admin"),
      "@/app/api": mainApp("app/api"),
      "@/app": mainApp("app"),
    },
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      exclude: [
        "node_modules/**",
        "tests/setup.ts",
        "tests/unit/setup.ts",
        "**/*.test.ts",
        "**/*.d.ts",
        "drizzle/**",
        "scripts/**",
      ],
    },
  },
  resolve: {
    alias: {
      "@supabase/ssr": supabaseSsr,
      "next/headers": nextHeaders,
      // Admin-side helpers import the canonical workspace package path
      // (@workspace/database/lib/idempotency). Alias it so vi.mock() can
      // intercept tests that exercise those helpers.
      "@workspace/database/lib/idempotency": db("lib/idempotency"),
      "@workspace/shared/constants": shared("constants"),
      "@workspace/shared/http-status": shared("http-status"),
      "@workspace/shared/pagination": shared("pagination"),
      "@workspace/shared/api-endpoints": shared("api-endpoints"),
      "@workspace/shared/analytics": shared("analytics"),
      "@workspace/shared/api-client": shared("api-client"),
      "@workspace/shared/utils": shared("utils"),
      "@workspace/shared/schemas": shared("schemas"),
      "@workspace/shared/routes": shared("routes"),
      "@workspace/shared": shared("index"),
      "@/db/db.server": db("db"),
      "@/db": db(""),
      "@/lib/security.server": db("lib/security"),
      "@/lib/auth.server": db("lib/auth"),
      "@/lib/db-locking": db("lib/db-locking"),
      "@/lib/supabase/admin": db("lib/supabase/admin"),
      "@/lib/supabase/server": db("lib/supabase/server"),
      "@/lib/supabase/client": db("lib/supabase/client"),
      "@/lib/supabase": db("lib/supabase"),
      "@/utils/supabase/server": db("lib/supabase/server"),
      "@/utils/supabase/client": db("lib/supabase/client"),
      "@/utils/supabase/admin": db("lib/supabase/admin"),
      "@/lib/http-status": shared("http-status"),
      "@/lib/pagination": shared("pagination"),
      "@/lib/api-endpoints": shared("api-endpoints"),
      "@/lib/api-client": shared("api-client"),
      "@/lib/utils": shared("utils"),
      "@/lib/schemas": shared("schemas"),
      "@/lib/api-auth": adminApp("lib/api-auth"),
      "@/lib/date-range": adminApp("lib/date-range"),
      "@/lib/idempotency": adminApp("lib/idempotency"),
      "@/lib": shared(""),
      "@/services/admin.client": adminApp("services/admin.client"),
      "@/services/chat.client": mainApp("services/chat.client"),
      "@/services/banner.server": db("services/banner.server"),
      "@/services/categoryCard.server": db("services/categoryCard.server"),
      "@/services": db("services"),
      "@/components/admin": adminApp("components/admin"),
      "@/components/store": mainApp("components/store"),
      "@/components/account": mainApp("components/account"),
      "@/components/products": mainApp("components/products"),
      "@/components/sections": mainApp("components/sections"),
      "@/components/layout": mainApp("components/layout"),
      "@/components/ui": ui("components"),
      "@/components/image-uploader": adminApp("components/image-uploader"),
      "@/components": mainApp("components"),
      "@/hooks/useMobile": ui("hooks/use-mobile"),
      "@/hooks": mainApp("hooks"),
      "@/types/admin": db("types/admin"),
      "@/types/api": db("types/api"),
      "@/types/database": db("types/database"),
      "@/types/order": db("types/order"),
      "@/types": shared("types"),
      "@/agent": mainApp("agent"),
    },
  },
});
